module.exports = {
  HEALTH_STATUS_UP: 'up',
  HEALTH_STATUS_DOWN: 'down',
  HEALTHY_STATUS_MESSAGE: 'OK',
  CONFIG_REDIS_URL_KEY: 'redisurl',
  CONFIG_CONNECTION_STRING_KEY: 'connectionstring',
  CONFIG_REDIS_CONNECTION_STRING_KEY: 'redisconnectionstring',
  REDIS_PROTOCOL: 'redis://',
  CONFIG_REDIS_TYPE: 'redis',
  REDIS_PORT_SECURE: '6380',
  POSTGRES_DIALECT: 'postgres',
  CONFIG_POSTGRES_URL_KEY: 'postgresurl',
  POSTGRES_CONNECTION_PREFIX: 'postgres://',
  CONFIG_SEQUELIZE_TYPE: 'sequelize',
  CONFIG_DATABASE_KEY: 'database',
  CONFIG_DEVICES_API_KEY: 'devices',
  CONFIG_API_TYPE: 'api',
  CONFIG_IDENTIFYING_PARTY_SECTION: 'identifyingParty',
  CONFIG_OIDC_SECTION: 'oidc',
};
